# action.yml
name: 'GBDK Builder'
description: 'Build gbdbk projects'
inputs:
  subdirectory:
    description: 'Path to sources'
    required: false
    default: '.'
  output-name:
    description: 'Changes the name of the resulting file. <output-name>.gb will be the result.'
    required: false
    default: 'game'
  source:
    description: 'Main source filename'
    required: false
    default: 'main.c'
branding:
  icon: play-circle
  color: yellow
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.subdirectory }}
    - ${{ inputs.output-name }}
    - ${{ inputs.source }}
